name: CI
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/convisocli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       CONVISO_COMPANY_ID: 553
       FLOW_PROJECT_CODE: "t4HsHF7GGJ6DlzPF"
   steps:
   - uses: actions/checkout@v3

   - name: Run SAST
     run: conviso sast run
   - name: Run SCA
     run: conviso sca run
